### ISSUE TITLE
Getting EURO symbol instead of aadha ka(क् e.g. क्या) in Chanakya font

### ISSUE THREAD

**Issue by cksachdev** [assistech-iitdelhi/InDesignFontConverters#12]
I have a document which uses Chanakya font, after installing Chanakya font, instead of "half ka" क् e.g. क्या, I am getting €(EURO) symbol. I noticed there are two different versions of chanakya tsv files in the repo. Could you please point me to the right version of Chanakya font to download.Below are few sample screenshots:
![image](https://user-images.githubusercontent.com/37770/64955340-a15de700-d8a5-11e9-89d6-a9a93688e856.png)

![image](https://user-images.githubusercontent.com/37770/64955362-ae7ad600-d8a5-11e9-835a-dbad681643ec.png)

![image](https://user-images.githubusercontent.com/37770/64955386-bb97c500-d8a5-11e9-8333-30a7b93540c6.png)

![image](https://user-images.githubusercontent.com/37770/64955399-c5212d00-d8a5-11e9-808f-27b1af11daf7.png)

![image](https://user-images.githubusercontent.com/37770/64956336-fb5fac00-d8a7-11e9-9ac6-b9cf29cf3a36.png)

**Comment by himanshugarg** [comment]
Thanks for the bug report. Do you have an InDesign file / sample text on which I can try this.

**Comment by cksachdev** [comment]
@himanshugarg No, I don't have an Indesign file currently. I am converting MS Word doc to Indesign and I installed the font after converting PFB file from https://sites.google.com/site/technicalhindi/about/_draft_post and converting PFB file to ttf file. Attaching sample MS Word doc for your reference:

[sample chanakya doc.zip](https://github.com/assistech-iitdelhi/InDesignFontConverters/files/3616193/sample.chanakya.doc.zip)

**Comment by himanshugarg** [comment]
ok checking. thanks

**Comment by himanshugarg** [comment]
ok checking. thanks

**Comment by himanshugarg** [comment]
Just checked. The font file that I have shows the same euro character. I think this text uses a customized variant of the font. If you are looking to convert then you need to edit the relevant tsv file. Hope this helps. Let me know if it doesn't.

![image](https://user-images.githubusercontent.com/2392803/65003248-4d8ae680-d915-11e9-9189-6e46f4e2da56.png)

If you are looking for the font you could write to sales@summitindia.com to get connected to their engg, depending upon your requirement. They are apparently the creators of the original Chanakya font.
